version: '3.4'

services:
  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8080:80"
      - "44399:443"
  books:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8081:80"
      - "44398:443"

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8082:80"
      - "44397:443"

  sqlserver:
    environment:
      - ACCEPT_EULA:Y
      - SA_PASSWORD:12345678a
      - MSSQL_PID:Express
    ports:
      - 1433:1433
    volumes:
      - ${APPDATA}/ASP.NET/DBs:/var/opt/mssql
